create generate page using  html & css
GSG-CF04/PiX-Quotes pull request #33
Opened 2021-11-30 19:55 UTC by A7medhq

#relates #14

Time taken: 1 hour

2021-11-30 22:50 UTC, kakashii7 approved these changes
good job

2021-11-30 23:11 UTC, IsraaAmani approved these changes

2021-12-01 07:02 UTC, Ibrahim-Jarada requested changes

2021-12-01 07:02 UTC, Ibrahim-Jarada commented on generate.html
> +          class="footer-btns"
You used <img> as a button.
To enhance SEO and Accessibility, put your `<img> ` inside `<button>`
Like this `<button><img /></button>`
In order to keep the `<img>` style you can give the button this style class
```
.img-btns {
background-color: transparent;
    border: 0;
}
```

2021-12-01 23:20 UTC, Ibrahim-Jarada approved these changes

2021-12-01 23:43 UTC, merged