create html and css for category page
GSG-CF04/PiX-Quotes pull request #35
Opened 2021-12-01 09:38 UTC by IsraaAmani

2021-12-01 14:35 UTC, A7medhq approved these changes

2021-12-02 06:25 UTC, Ibrahim-Jarada requested changes

2021-12-02 06:25 UTC, Ibrahim-Jarada commented on category.html
> +        <button class="nav-btns" type="submit" onclick="location.href='favorites.html'">Favorites</button>
There is no need to give `type="submit"` to your button because it is by default
Also you haven't a form in your page

2021-12-02 06:25 UTC, Ibrahim-Jarada commented on category.html
>      <title>Download</title>
Wrong stylesheet link `<link rel="stylesheet" href="css/download.css" />
Change it to href="css/category.css" 
`

2021-12-02 07:53 UTC, Ibrahim-Jarada approved these changes

2021-12-02 08:12 UTC, kakashii7 approved these changes
good job

2021-12-02 08:12 UTC, merged